[workspace]
authors = ["hyzhou"]
channels = ["conda-forge"]
name = "navsim"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.12.*"

[pypi-dependencies]
torch = { version = "==2.0.1", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { version = "==0.15.2", index = "https://download.pytorch.org/whl/cu118"}
scikit-learn = "==1.2.2"
positional-encodings = "==6.0.1"
aioboto3 = ">=14.1.0, <15"
aiofiles = ">=24.1.0, <25"
bokeh = "==2.4.3"
casadi = ">=3.7.0, <4"
control = "==0.9.1"
fiona = ">=1.10.1, <2"
geopandas = ">=0.12.1"
guppy3 = "==3.1.2"
hydra-core = "==1.2.0"
joblib = ">=1.4.2, <2"
matplotlib = ">=3.9.4, <4"
nest-asyncio = ">=1.6.0, <2"
numpy = "==1.23.4"
opencv-python = "==4.9.0.80"
pandas = ">=2.2.3, <3"
pillow = ">=11.2.1, <12"
psutil = ">=7.0.0, <8"
pyarrow = ">=19.0.1, <20"
pyinstrument = ">=5.0.1, <6"
pyogrio = ">=0.10.0, <0.11"
pyquaternion = ">=0.9.5"
pytest = ">=8.3.5, <9"
rasterio = ">=1.3.11, <2"
ray = ">=2.44.1, <3"
retry = ">=0.9.2, <0.10"
rtree = ">=1.4.0, <2"
scipy = ">=1.13.1, <2"
selenium = ">=4.31.0, <5"
setuptools = "==65.5.1"
shapely = ">=2.0.0"
sqlalchemy = "==1.4.27"
sympy = ">=1.13.3, <2"
tornado = ">=6.4.2, <7"
tqdm = ">=4.67.1, <5"
ujson = ">=5.10.0, <6"
pytorch-lightning = "==2.2.1"
tensorboard = "==2.16.2"
protobuf = "==4.25.3"
notebook = ">=7.4.0, <8"
timm = ">=1.0.15, <2"
navsim = { path = ".", editable = false }
nuplan-devkit = { git = "https://github.com/motional/nuplan-devkit", rev = "nuplan-devkit-v1.2" }


